spring:
  application:
    name: framework
server:
  port: 8080



##service.context-path= //
#server.tomcat.uri-encoding=UTF-8
#spring.thymeleaf.cache=false
#spring.thymeleaf.mode=LEGACYHTML5
#
##\u65E5\u5FD7
#logging.config=classpath:config/logback-spring.xml
#
##\u6570\u636E\u6E90\u8FDE\u63A5







#spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.url=jdbc:mysql://211.159.206.174:3306/sxtj?useUnicode=true&characterEncoding=utf8&useSSL=false
#spring.datasource.username=root
#spring.datasource.password=K%tg3yDF=U.8Rq2I
#
##\u6570\u636E\u5E93\u8FDE\u63A5\u6C60\u8BBE\u7F6E
#spring.datasource.initialSize=20
#spring.datasource.minIdle=20
#spring.datasource.maxActive=100
#spring.datasource.maxWait=60000
#spring.datasource.timeBetweenEvictionRunsMillis=60000
#spring.datasource.minEvictableIdleTimeMillis=300000
#spring.datasource.validationQuery=SELECT 1 FROM DUAL
#spring.datasource.testWhileIdle=true
#spring.datasource.testOnBorrow=false
#spring.datasource.testOnReturn=false
#spring.datasource.poolPreparedStatements=true
#spring.datasource.maxPoolPreparedStatementPerConnectionSize=20
#spring.datasource.filters=stat,wall,log4j
#spring.datasource.connectionProperties=druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#
#
##mybatis \u5B9E\u4F53\u7C7B\u6620\u5C04\u914D\u7F6E
#mybatis.typeAliasesPackage=com.tencent.admin.bean
#mybatis.config-location=classpath:config/mybatis-config.xml
#
##\u5FAE\u4FE1\u516C\u4F17\u53F7\u914D\u7F6E
#wx.appId=wx7ffd297e337e9290
#wx.appSecret=486eec0c62986ca1a57f217bc2da81e5
#
########################\u7B2C\u4E09\u65B9\u7CFB\u7EDF\u5730\u5740########################
##############\u5916\u7F51\u524D\u7F6E###################
#external.network.preposition=http://localhost:8082/noCriminalproof/statisticsA
##############\u5185\u7F51\u524D\u7F6E###################
#intranet.preposition=http://localhost:8082/dictionnary/selectDictionary?code=140000&rank=2
#
#

